version: '3.7'

services:
  pysonet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  pysonet_db:
    image: postgres:12.0-alpine
    volumes:
      - pysonet_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_DB=django_movie_dev

volumes:
  pysonet_postgres_data:
